
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Formatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush
 */
public class AddEntry extends javax.swing.JFrame {

 
    /**
     * Creates new form AddEntry
     */
    public AddEntry() {
        setResizable(false);
        initComponents();
        setIcon();
        setTitle("Add Entry");
        setComboBox();
        setTitle("Customer Details");
        setCustomerComboBox();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageHeading = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        date = new javax.swing.JLabel();
        eno = new javax.swing.JLabel();
        selecteno = new javax.swing.JTextField();
        cquantity = new javax.swing.JLabel();
        selectcquantity = new javax.swing.JTextField();
        product = new javax.swing.JLabel();
        selectfilling = new javax.swing.JTextField();
        selectproduct = new javax.swing.JComboBox<>();
        crate = new javax.swing.JLabel();
        srate = new javax.swing.JLabel();
        selectcrate = new javax.swing.JTextField();
        plotnumber = new javax.swing.JLabel();
        stockname = new javax.swing.JLabel();
        selectstockname = new javax.swing.JComboBox<>();
        rent = new javax.swing.JLabel();
        selectstockquantity = new javax.swing.JTextField();
        filling = new javax.swing.JLabel();
        stockquantity = new javax.swing.JLabel();
        selectsrate = new javax.swing.JTextField();
        selectrent = new javax.swing.JTextField();
        addentrybutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        selectdate = new com.toedter.calendar.JDateChooser();
        back = new javax.swing.JButton();
        CheckProfit = new javax.swing.JPanel();
        ClickHere = new javax.swing.JButton();
        LMessage = new javax.swing.JLabel();
        ComingProfit = new javax.swing.JTextField();
        selectplotnumber = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PageHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PageHeading.setForeground(new java.awt.Color(0, 102, 102));
        PageHeading.setText("Add Entry:-");

        Heading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 0, 153));
        Heading.setText("PAWAN Builder Material Supplier");

        note.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        note.setForeground(new java.awt.Color(255, 0, 0));
        note.setText("Note :- All Entry Must be filled before submission ");

        date.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date.setText("Date                  :");

        eno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        eno.setText("Entry Number      :");

        selecteno.setText("Enter your Entry Number");
        selecteno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectenoMouseClicked(evt);
            }
        });

        cquantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cquantity.setText("Enter Quantity(C) :");

        selectcquantity.setText("Quantity for Customer");
        selectcquantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectcquantityMouseClicked(evt);
            }
        });
        selectcquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcquantityActionPerformed(evt);
            }
        });

        product.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        product.setText("Product              :");

        selectfilling.setText("Filling on stock");
        selectfilling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectfillingMouseClicked(evt);
            }
        });
        selectfilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectfillingActionPerformed(evt);
            }
        });

        selectproduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sand", "Dust", "Rodi", "Cement", "Brick" }));
        selectproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectproductActionPerformed(evt);
            }
        });

        crate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        crate.setText("Enter Rate(C)      :");

        srate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        srate.setText("Rate(S)             :");

        selectcrate.setText("Rate to Customer");
        selectcrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectcrateMouseClicked(evt);
            }
        });
        selectcrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcrateActionPerformed(evt);
            }
        });

        plotnumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber.setText("Plot Number        :");

        stockname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname.setText("Stock Name        :");

        selectstockname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectstockname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectstocknameActionPerformed(evt);
            }
        });

        rent.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rent.setText("Rent                  :");

        selectstockquantity.setText("Quantity from Stock");
        selectstockquantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectstockquantityMouseClicked(evt);
            }
        });
        selectstockquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectstockquantityActionPerformed(evt);
            }
        });

        filling.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        filling.setText("Filling on Stock     :");

        stockquantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockquantity.setText("Enter Quantity(S) :");

        selectsrate.setText("Rent From Stock");
        selectsrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectsrateMouseClicked(evt);
            }
        });
        selectsrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectsrateActionPerformed(evt);
            }
        });

        selectrent.setText("Rent to Customer");
        selectrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectrentMouseClicked(evt);
            }
        });
        selectrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectrentActionPerformed(evt);
            }
        });

        addentrybutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addentrybutton.setText("Add Entry");
        addentrybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addentrybuttonActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        selectdate.setDateFormatString("yyyy-MM-dd");
        selectdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        CheckProfit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Check Profit", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ClickHere.setText("Click Here");
        ClickHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickHereActionPerformed(evt);
            }
        });

        LMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LMessage.setForeground(new java.awt.Color(255, 0, 0));
        LMessage.setText("Click Here ,after Filling all the Enteries");

        ComingProfit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout CheckProfitLayout = new javax.swing.GroupLayout(CheckProfit);
        CheckProfit.setLayout(CheckProfitLayout);
        CheckProfitLayout.setHorizontalGroup(
            CheckProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckProfitLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CheckProfitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClickHere, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(ComingProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        CheckProfitLayout.setVerticalGroup(
            CheckProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckProfitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CheckProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComingProfit)
                    .addComponent(ClickHere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(addentrybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cquantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(crate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(plotnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectdate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(stockname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectstockname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(selectproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(filling, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(selecteno, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                    .addComponent(selectcquantity))
                                                .addGap(95, 95, 95)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(srate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stockquantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectstockquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectfilling, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectsrate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(selectcrate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(selectrent)
                                            .addComponent(selectplotnumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CheckProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectstockname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(selectdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectstockquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectsrate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecteno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectcquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filling, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectfilling, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectcrate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectrent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plotnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectplotnumber)
                                .addGap(1, 1, 1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CheckProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(addentrybutton)
                    .addComponent(resetbutton))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectcquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcquantityActionPerformed

    private void selectfillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectfillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectfillingActionPerformed

    private void selectproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectproductActionPerformed

    private void selectcrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcrateActionPerformed

    private void selectstocknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectstocknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectstocknameActionPerformed

    private void selectstockquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectstockquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectstockquantityActionPerformed

    private void selectsrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectsrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectsrateActionPerformed

    private void selectrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectrentActionPerformed

    private void selectenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectenoMouseClicked
        selecteno.setText("");
    }//GEN-LAST:event_selectenoMouseClicked

    private void selectcquantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectcquantityMouseClicked
        selectcquantity.setText("");
    }//GEN-LAST:event_selectcquantityMouseClicked

    private void selectcrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectcrateMouseClicked
       selectcrate.setText("");
    }//GEN-LAST:event_selectcrateMouseClicked

    private void selectrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectrentMouseClicked
     selectrent.setText("");
    }//GEN-LAST:event_selectrentMouseClicked

    private void selectstockquantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectstockquantityMouseClicked
       selectstockquantity.setText("");
    }//GEN-LAST:event_selectstockquantityMouseClicked

    private void selectsrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectsrateMouseClicked
        selectsrate.setText("");
    }//GEN-LAST:event_selectsrateMouseClicked

    private void selectfillingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectfillingMouseClicked
      selectfilling.setText("");
    }//GEN-LAST:event_selectfillingMouseClicked

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
     selectcquantity.setText("");
     selectcrate.setText("");
     selecteno.setText("");
     selectfilling.setText("");
     selectrent.setText("");
     selectsrate.setText("");
     selectstockquantity.setText("");
     selectsrate.setText("");
     selectstockquantity.setText("");
     selectrent.setText("");
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void addentrybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addentrybuttonActionPerformed
        try{
        int cquan = Integer.parseInt(selectcquantity.getText());
        double crt = Double.parseDouble(selectcrate.getText());
        int rnt = Integer.parseInt(selectrent.getText());
        int squan = Integer.parseInt(selectstockquantity.getText());
        double srt = Double.parseDouble(selectsrate.getText());
        int fill = Integer.parseInt(selectfilling.getText());
        double incm = cquan * crt;
        double outg = squan * srt + fill;
        double result = incm - outg;
        result =result-rnt;
        ComingProfit.setText(" "+result);   
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddEntry values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
          int cquant=Integer.parseInt(selectcquantity.getText());
         double curate=Double.parseDouble(selectcrate.getText());
         int squant =Integer.parseInt(selectstockquantity.getText());
         double strate=Double.parseDouble(selectsrate.getText());
         int fillng=Integer.parseInt(selectfilling.getText());
         ps.setString(1, df.format(selectdate.getDate()));
         ps.setInt(2, Integer.parseInt(selecteno.getText()));
         ps.setInt(3,cquant);
         String prod=selectproduct.getSelectedItem().toString();
         ps.setString(4, prod);
         ps.setDouble(5, curate);
         ps.setInt(6,Integer.parseInt(selectrent.getText()));
         String plotN=selectplotnumber.getSelectedItem().toString();
         ps.setString(7,plotN);
         String stnm= selectstockname.getSelectedItem().toString();
         ps.setString(8,stnm);
         ps.setInt(9,squant);
         ps.setDouble(10,strate);
         ps.setInt(11, fillng);         
         ps.setDouble(12,Double.parseDouble(ComingProfit.getText()));
        
         double camt=cquant*curate;
         double samt=squant*strate+fillng;
         ps.setDouble(13, camt);
         ps.setDouble(14, samt);
         ps.execute();
        JOptionPane.showMessageDialog(null, "Your entry added Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addentrybuttonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       close();
       MenuSelection ms=new MenuSelection();
       ms.setVisible(true);
       
    }//GEN-LAST:event_backActionPerformed

    private void ClickHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickHereActionPerformed
        int cquan = Integer.parseInt(selectcquantity.getText());
        double crt = Double.parseDouble(selectcrate.getText());
        int rnt = Integer.parseInt(selectrent.getText());
        int squan = Integer.parseInt(selectstockquantity.getText());
        double srt = Double.parseDouble(selectsrate.getText());
        int fill = Integer.parseInt(selectfilling.getText());
        double incm = cquan * crt;
        double outg = squan * srt + fill;
        double result = incm - outg;
        result =result-rnt;
        ComingProfit.setText(" "+result);
    }//GEN-LAST:event_ClickHereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckProfit;
    private javax.swing.JButton ClickHere;
    private javax.swing.JTextField ComingProfit;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel PageHeading;
    private javax.swing.JButton addentrybutton;
    private javax.swing.JButton back;
    private javax.swing.JLabel cquantity;
    private javax.swing.JLabel crate;
    private javax.swing.JLabel date;
    private javax.swing.JLabel eno;
    private javax.swing.JLabel filling;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel note;
    private javax.swing.JLabel plotnumber;
    private javax.swing.JLabel product;
    private javax.swing.JLabel rent;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField selectcquantity;
    private javax.swing.JTextField selectcrate;
    private com.toedter.calendar.JDateChooser selectdate;
    private javax.swing.JTextField selecteno;
    private javax.swing.JTextField selectfilling;
    public javax.swing.JComboBox<String> selectplotnumber;
    private javax.swing.JComboBox<String> selectproduct;
    private javax.swing.JTextField selectrent;
    private javax.swing.JTextField selectsrate;
    public javax.swing.JComboBox<String> selectstockname;
    private javax.swing.JTextField selectstockquantity;
    private javax.swing.JLabel srate;
    private javax.swing.JLabel stockname;
    private javax.swing.JLabel stockquantity;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\truck.png")));
    }
    public void close(){
    WindowEvent we=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
}   

    private void setComboBox() {
    try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select NameOfStock from StockDetails");
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
           selectstockname.addItem(rs.getString("NameOfStock"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox1");
       }
    }
    private void setCustomerComboBox() {
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select * from CustomerDetail");
           ResultSet rs=ps.executeQuery();
           PreparedStatement ps1=con.prepareStatement("select * from rentcustentry");
           ResultSet rs1=ps1.executeQuery();
           while(rs.next()){
           selectplotnumber.addItem(rs.getString("CustomerPlotNumber"));
           }
           while(rs1.next()){
           selectplotnumber.addItem(rs1.getString("PlotNumber"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox2");
       }
    }
}
