
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush
 */
public class AddMoney extends javax.swing.JFrame {

    /**
     * Creates new form AddMoney
     */
    public AddMoney() {
        initComponents();
        setComboBox();
        setCustomer();
         setCustomerComboBox();
         setTitle("Add Money");
         setResizable(false);
         setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterSHeading = new javax.swing.JLabel();
        MainHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        stockName = new javax.swing.JPanel();
        ssubmit = new javax.swing.JButton();
        sselectstockname = new javax.swing.JComboBox<>();
        stockname = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        sdate = new com.toedter.calendar.JDateChooser();
        plotnumber3 = new javax.swing.JLabel();
        samount = new javax.swing.JTextField();
        plotnumber9 = new javax.swing.JLabel();
        seno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        plotnumber1 = new javax.swing.JLabel();
        pnplotnumber = new javax.swing.JComboBox<>();
        pnsubmit = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        pndate = new com.toedter.calendar.JDateChooser();
        plotnumber2 = new javax.swing.JLabel();
        pnamount = new javax.swing.JTextField();
        plotnumber4 = new javax.swing.JLabel();
        pneno = new javax.swing.JTextField();
        driverconductor = new javax.swing.JPanel();
        dcsubmit = new javax.swing.JButton();
        dcemployee = new javax.swing.JComboBox<>();
        stockname2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        dcdate = new com.toedter.calendar.JDateChooser();
        plotnumber5 = new javax.swing.JLabel();
        dcamount = new javax.swing.JTextField();
        dceno = new javax.swing.JTextField();
        plotnumber11 = new javax.swing.JLabel();
        stockName3 = new javax.swing.JPanel();
        rcsubmit = new javax.swing.JButton();
        stockname3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        rcdate = new com.toedter.calendar.JDateChooser();
        rcname = new javax.swing.JComboBox<>();
        plotnumber6 = new javax.swing.JLabel();
        rcamount = new javax.swing.JTextField();
        plotnumber8 = new javax.swing.JLabel();
        rceno = new javax.swing.JTextField();
        tm = new javax.swing.JPanel();
        tmsubmit = new javax.swing.JButton();
        stockname4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        tmdate = new com.toedter.calendar.JDateChooser();
        plotnumber7 = new javax.swing.JLabel();
        tmamount = new javax.swing.JTextField();
        plotnumber10 = new javax.swing.JLabel();
        tmeno = new javax.swing.JTextField();
        tmname1 = new javax.swing.JComboBox<>();
        tm1 = new javax.swing.JPanel();
        pssubmit = new javax.swing.JButton();
        stockname6 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        psdate = new com.toedter.calendar.JDateChooser();
        plotnumber12 = new javax.swing.JLabel();
        psreason = new javax.swing.JTextField();
        plotnumber13 = new javax.swing.JLabel();
        pseno = new javax.swing.JTextField();
        psamount = new javax.swing.JTextField();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RegisterSHeading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RegisterSHeading.setForeground(new java.awt.Color(0, 51, 153));
        RegisterSHeading.setText("PAWAN Building material Supplier");

        MainHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MainHeading.setForeground(new java.awt.Color(0, 102, 102));
        MainHeading.setText("Add Money :-");

        stockName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "To Stock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        ssubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ssubmit.setText("Submit");
        ssubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubmitActionPerformed(evt);
            }
        });

        sselectstockname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stockname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname.setText("Stock Name  :");

        date1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date1.setText("Date           :");

        sdate.setDateFormatString("yyyy-MM-dd");
        sdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber3.setText("Amount       :");

        samount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        samount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samountActionPerformed(evt);
            }
        });

        plotnumber9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber9.setText("Entry Number :");

        seno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stockNameLayout = new javax.swing.GroupLayout(stockName);
        stockName.setLayout(stockNameLayout);
        stockNameLayout.setHorizontalGroup(
            stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockNameLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(ssubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(stockNameLayout.createSequentialGroup()
                .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockNameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plotnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockname))
                        .addGap(14, 14, 14)
                        .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(samount)
                            .addComponent(sdate, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(sselectstockname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(stockNameLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(plotnumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seno)))
                .addContainerGap())
        );
        stockNameLayout.setVerticalGroup(
            stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber9)
                    .addComponent(seno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sselectstockname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockname))
                .addGap(18, 18, 18)
                .addGroup(stockNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber3)
                    .addComponent(samount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ssubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "To PlotNumber", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        plotnumber1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber1.setText("Plot Number :");

        pnsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnsubmit.setText("Submit");
        pnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnsubmitActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date.setText("Date          :");

        pndate.setDateFormatString("yyyy-MM-dd");
        pndate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber2.setText("Amount       :");

        pnamount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        plotnumber4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber4.setText("Entry Number :");

        pneno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(pndate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(plotnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pnamount))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plotnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plotnumber4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pneno)
                            .addComponent(pnplotnumber, 0, 139, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(pnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber4)
                    .addComponent(pneno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber1)
                    .addComponent(pnplotnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber2)
                    .addComponent(pnamount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnsubmit)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        driverconductor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Driver/Conductor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        dcsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dcsubmit.setText("Submit");
        dcsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcsubmitActionPerformed(evt);
            }
        });

        dcemployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver", "Conductor" }));
        dcemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stockname2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname2.setText("Employee    :");

        date3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date3.setText("Date           :");

        dcdate.setDateFormatString("yyyy-MM-dd");
        dcdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber5.setText("Amount       :");

        dcamount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dcamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcamountActionPerformed(evt);
            }
        });

        dceno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcenoActionPerformed(evt);
            }
        });

        plotnumber11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber11.setText("Entry Number:");

        javax.swing.GroupLayout driverconductorLayout = new javax.swing.GroupLayout(driverconductor);
        driverconductor.setLayout(driverconductorLayout);
        driverconductorLayout.setHorizontalGroup(
            driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverconductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverconductorLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(dcsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(driverconductorLayout.createSequentialGroup()
                        .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(driverconductorLayout.createSequentialGroup()
                                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plotnumber11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dceno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addGroup(driverconductorLayout.createSequentialGroup()
                                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stockname2)
                                    .addComponent(plotnumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcemployee, 0, 133, Short.MAX_VALUE)
                                    .addComponent(dcamount))))
                        .addContainerGap())))
        );
        driverconductorLayout.setVerticalGroup(
            driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverconductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dceno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotnumber11))
                .addGap(18, 18, 18)
                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockname2)
                    .addComponent(dcemployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(driverconductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber5)
                    .addComponent(dcamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dcsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stockName3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Rent Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rcsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rcsubmit.setText("Submit");
        rcsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcsubmitActionPerformed(evt);
            }
        });

        stockname3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname3.setText("Name         :");

        date4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date4.setText("Date           :");

        rcdate.setDateFormatString("yyyy-MM-dd");
        rcdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber6.setText("Amount       :");

        rcamount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        plotnumber8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber8.setText("Entry Number:");

        rceno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout stockName3Layout = new javax.swing.GroupLayout(stockName3);
        stockName3.setLayout(stockName3Layout);
        stockName3Layout.setHorizontalGroup(
            stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockName3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(rcsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(stockName3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockname3)
                    .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotnumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotnumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcamount)
                    .addComponent(rceno)
                    .addComponent(rcdate, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(rcname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        stockName3Layout.setVerticalGroup(
            stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockName3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rcdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plotnumber8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rceno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockname3)
                    .addComponent(rcname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stockName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plotnumber6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rcamount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rcsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tm.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Truck Maintenance", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tmsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tmsubmit.setText("Submit");
        tmsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmsubmitActionPerformed(evt);
            }
        });

        stockname4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname4.setText("Name         :");

        date5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date5.setText("Date           :");

        tmdate.setDateFormatString("yyyy-MM-dd");
        tmdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber7.setText("Amount       :");

        tmamount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        plotnumber10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber10.setText("Entry Number:");

        tmeno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tmname1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Repairing", "Other" }));
        tmname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmname1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tmLayout = new javax.swing.GroupLayout(tm);
        tm.setLayout(tmLayout);
        tmLayout.setHorizontalGroup(
            tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tmLayout.createSequentialGroup()
                        .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tmLayout.createSequentialGroup()
                                .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tmLayout.createSequentialGroup()
                                .addComponent(plotnumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tmdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmeno)))
                    .addGroup(tmLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(tmsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tmLayout.createSequentialGroup()
                        .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tmLayout.createSequentialGroup()
                                .addComponent(stockname4)
                                .addGap(25, 25, 25))
                            .addGroup(tmLayout.createSequentialGroup()
                                .addComponent(plotnumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tmamount)
                            .addComponent(tmname1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tmLayout.setVerticalGroup(
            tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tmdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmeno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotnumber10))
                .addGap(18, 18, 18)
                .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockname4)
                    .addComponent(tmname1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plotnumber7)
                    .addComponent(tmamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tmsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tm1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Personal Spend\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        pssubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pssubmit.setText("Submit");
        pssubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssubmitActionPerformed(evt);
            }
        });

        stockname6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname6.setText("Reason       :");

        date6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date6.setText("Date           :");

        psdate.setDateFormatString("yyyy-MM-dd");
        psdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        plotnumber12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber12.setText("Amount       :");

        psreason.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        plotnumber13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber13.setText("Entry Number:");

        pseno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        psamount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout tm1Layout = new javax.swing.GroupLayout(tm1);
        tm1.setLayout(tm1Layout);
        tm1Layout.setHorizontalGroup(
            tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tm1Layout.createSequentialGroup()
                        .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plotnumber13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pseno)))
                    .addGroup(tm1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(pssubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tm1Layout.createSequentialGroup()
                        .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockname6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plotnumber12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psreason)
                            .addComponent(psamount))))
                .addContainerGap())
        );
        tm1Layout.setVerticalGroup(
            tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(psdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pseno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotnumber13))
                .addGap(18, 18, 18)
                .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockname6)
                    .addComponent(psreason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber12)
                    .addComponent(psamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pssubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(RegisterSHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(driverconductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307)
                        .addComponent(MainHeading)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterSHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainHeading)
                    .addComponent(Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stockName3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(driverconductor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ssubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubmitActionPerformed
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToS values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(sdate.getDate()));
         ps.setInt(2, Integer.parseInt(seno.getText()));        
         String plotN=sselectstockname.getSelectedItem().toString();
         ps.setString(3,plotN);
         ps.setInt(4,Integer.parseInt(samount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }
    }//GEN-LAST:event_ssubmitActionPerformed

    private void pnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnsubmitActionPerformed
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToPN values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(pndate.getDate()));
         ps.setInt(2, Integer.parseInt(pneno.getText()));        
         String plotN=pnplotnumber.getSelectedItem().toString();
         ps.setString(3,plotN);
         ps.setInt(4,Integer.parseInt(pnamount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }
    }//GEN-LAST:event_pnsubmitActionPerformed

    private void samountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samountActionPerformed

    private void dcsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcsubmitActionPerformed
         try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToDC values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(dcdate.getDate()));
         ps.setInt(2, Integer.parseInt(dceno.getText()));        
         String employee=dcemployee.getSelectedItem().toString();
         ps.setString(3,employee);
         ps.setInt(4,Integer.parseInt(dcamount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }
    }//GEN-LAST:event_dcsubmitActionPerformed

    private void dcamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcamountActionPerformed

    private void rcsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcsubmitActionPerformed
         try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToRC values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(rcdate.getDate()));
         ps.setInt(2, Integer.parseInt(rceno.getText()));        
         String name=rcname.getSelectedItem().toString();
         ps.setString(3,name);
         ps.setInt(4,Integer.parseInt(rcamount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }

    }//GEN-LAST:event_rcsubmitActionPerformed

    private void tmsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmsubmitActionPerformed
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToTm values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(tmdate.getDate()));
         ps.setInt(2, Integer.parseInt(tmeno.getText()));        
         String name=tmname1.getSelectedItem().toString();
         ps.setString(3,name);
         ps.setInt(4,Integer.parseInt(tmamount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }
    }//GEN-LAST:event_tmsubmitActionPerformed

    private void senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senoActionPerformed

    private void tmname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmname1ActionPerformed

    private void pssubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssubmitActionPerformed
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
         PreparedStatement ps=con.prepareStatement("insert into AddMoneyToPS values(?,?,?,?)");
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
         ps.setString(1, df.format(psdate.getDate()));
         ps.setInt(2, Integer.parseInt(pseno.getText()));        
         ps.setString(3,psreason.getText());         
         ps.setInt(4,Integer.parseInt(psamount.getText()));
         ps.execute();
        JOptionPane.showMessageDialog(null, "Amount Submit Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pssubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        close();
        MenuSelection ms=new MenuSelection();
        ms.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void dcenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel MainHeading;
    private javax.swing.JLabel RegisterSHeading;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private javax.swing.JTextField dcamount;
    private com.toedter.calendar.JDateChooser dcdate;
    public javax.swing.JComboBox<String> dcemployee;
    private javax.swing.JTextField dceno;
    private javax.swing.JButton dcsubmit;
    private javax.swing.JPanel driverconductor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel plotnumber1;
    private javax.swing.JLabel plotnumber10;
    private javax.swing.JLabel plotnumber11;
    private javax.swing.JLabel plotnumber12;
    private javax.swing.JLabel plotnumber13;
    private javax.swing.JLabel plotnumber2;
    private javax.swing.JLabel plotnumber3;
    private javax.swing.JLabel plotnumber4;
    private javax.swing.JLabel plotnumber5;
    private javax.swing.JLabel plotnumber6;
    private javax.swing.JLabel plotnumber7;
    private javax.swing.JLabel plotnumber8;
    private javax.swing.JLabel plotnumber9;
    private javax.swing.JTextField pnamount;
    private com.toedter.calendar.JDateChooser pndate;
    private javax.swing.JTextField pneno;
    public javax.swing.JComboBox<String> pnplotnumber;
    private javax.swing.JButton pnsubmit;
    private javax.swing.JTextField psamount;
    private com.toedter.calendar.JDateChooser psdate;
    private javax.swing.JTextField pseno;
    private javax.swing.JTextField psreason;
    private javax.swing.JButton pssubmit;
    private javax.swing.JTextField rcamount;
    private com.toedter.calendar.JDateChooser rcdate;
    private javax.swing.JTextField rceno;
    private javax.swing.JComboBox<String> rcname;
    private javax.swing.JButton rcsubmit;
    private javax.swing.JTextField samount;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JTextField seno;
    public javax.swing.JComboBox<String> sselectstockname;
    private javax.swing.JButton ssubmit;
    private javax.swing.JPanel stockName;
    private javax.swing.JPanel stockName3;
    private javax.swing.JLabel stockname;
    private javax.swing.JLabel stockname2;
    private javax.swing.JLabel stockname3;
    private javax.swing.JLabel stockname4;
    private javax.swing.JLabel stockname6;
    private javax.swing.JPanel tm;
    private javax.swing.JPanel tm1;
    private javax.swing.JTextField tmamount;
    private com.toedter.calendar.JDateChooser tmdate;
    private javax.swing.JTextField tmeno;
    private javax.swing.JComboBox<String> tmname1;
    private javax.swing.JButton tmsubmit;
    // End of variables declaration//GEN-END:variables
private void setCustomerComboBox() {
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select * from CustomerDetail");
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
           pnplotnumber.addItem(rs.getString("CustomerPlotNumber"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox");
       }
    }
private void setComboBox() {
    try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select NameOfStock from StockDetails");
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
           sselectstockname.addItem(rs.getString("NameOfStock"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox");
       }
    }
private void setCustomer(){
    try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select CustName from RentalCustomerDetails");
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
         rcname .addItem(rs.getString("CustName"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox");
       }
    }
 private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\truck.png")));
   
    }
     public void close(){
    WindowEvent we=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
}
}
