
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush
 */
public class AddRentEntry extends javax.swing.JFrame {

    /**
     * Creates new form AddRentEntry
     */
    public AddRentEntry() {
        initComponents();
        setCustomer();
        setTitle("Add Entry(For rent)");
        setResizable(false);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageHeading = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rent = new javax.swing.JLabel();
        selectstockname = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        eno = new javax.swing.JLabel();
        selectdate = new com.toedter.calendar.JDateChooser();
        selecteno = new javax.swing.JTextField();
        cquantity = new javax.swing.JLabel();
        selectcquantity = new javax.swing.JTextField();
        product = new javax.swing.JLabel();
        selectproduct = new javax.swing.JComboBox<>();
        plotnumber = new javax.swing.JLabel();
        selectplotnumber = new javax.swing.JTextField();
        stockname = new javax.swing.JLabel();
        selectrent = new javax.swing.JTextField();
        addentrybutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        customer = new javax.swing.JLabel();
        selectcustomer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PageHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PageHeading.setForeground(new java.awt.Color(0, 102, 102));
        PageHeading.setText("Add Entry(For Rent):-");

        Heading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 0, 153));
        Heading.setText("PAWAN Builder Material Supplier");

        note.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        note.setForeground(new java.awt.Color(255, 0, 0));
        note.setText("Note :- All Entry Must be filled before submission ");

        rent.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rent.setText("Rent                  :");

        selectstockname.setText("Enter Stock Name");
        selectstockname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectstocknameMouseClicked(evt);
            }
        });
        selectstockname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectstocknameActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date.setText("Date                  :");

        eno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        eno.setText("Entry Number      :");

        selectdate.setDateFormatString("yyyy-MM-dd");
        selectdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        selecteno.setText("Enter your Entry Number");
        selecteno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectenoMouseClicked(evt);
            }
        });

        cquantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cquantity.setText("Enter Quantity(C) :");

        selectcquantity.setText("Quantity for Customer");
        selectcquantity.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                selectcquantityAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        selectcquantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectcquantityMouseClicked(evt);
            }
        });
        selectcquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcquantityActionPerformed(evt);
            }
        });

        product.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        product.setText("Product              :");

        selectproduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sand", "Dust", "Rodi", "Cement", "Brick" }));
        selectproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectproductActionPerformed(evt);
            }
        });

        plotnumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        plotnumber.setText("Plot Number        :");

        selectplotnumber.setText("PlotNumber for Customer");
        selectplotnumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectplotnumberMouseClicked(evt);
            }
        });
        selectplotnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectplotnumberActionPerformed(evt);
            }
        });

        stockname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        stockname.setText("Stock Name        :");

        selectrent.setText("Rent to Customer");
        selectrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectrentMouseClicked(evt);
            }
        });
        selectrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectrentActionPerformed(evt);
            }
        });

        addentrybutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addentrybutton.setText("Add Entry");
        addentrybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addentrybuttonActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        customer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        customer.setText("Customer           :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cquantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectrent, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectstockname, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(selectdate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(selectproduct, 0, 139, Short.MAX_VALUE)
                                        .addComponent(selecteno, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(selectcquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(selectplotnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                    .addComponent(selectcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(plotnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stockname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(addentrybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecteno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectcquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectplotnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectstockname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectrent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(addentrybutton)
                    .addComponent(resetbutton))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(506, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectstocknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectstocknameMouseClicked
        selectstockname.setText("");
    }//GEN-LAST:event_selectstocknameMouseClicked

    private void selectstocknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectstocknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectstocknameActionPerformed

    private void selectenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectenoMouseClicked
        selecteno.setText("");
    }//GEN-LAST:event_selectenoMouseClicked

    private void selectcquantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectcquantityMouseClicked
        selectcquantity.setText("");
    }//GEN-LAST:event_selectcquantityMouseClicked

    private void selectcquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcquantityActionPerformed

    private void selectproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectproductActionPerformed

    private void selectplotnumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectplotnumberMouseClicked
       selectplotnumber.setText("");
    }//GEN-LAST:event_selectplotnumberMouseClicked

    private void selectplotnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectplotnumberActionPerformed
        selectplotnumber.setText("");
    }//GEN-LAST:event_selectplotnumberActionPerformed

    private void selectrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectrentMouseClicked
       selectrent.setText("");
    }//GEN-LAST:event_selectrentMouseClicked

    private void selectrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectrentActionPerformed

    private void addentrybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addentrybuttonActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
            PreparedStatement ps=con.prepareStatement("insert into RentCustEntry values(?,?,?,?,?,?,?,?)");
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            ps.setString(1, df.format(selectdate.getDate()));
            ps.setInt(2, Integer.parseInt(selecteno.getText()));
            ps.setInt(3,Integer.parseInt(selectcquantity.getText()));
            String cust=selectcustomer.getSelectedItem().toString();
            ps.setString(4, cust);
            String prod=selectproduct.getSelectedItem().toString();
           ps.setString(5, prod);
           ps.setString(6,selectplotnumber.getText());
           ps.setString(7,selectstockname.getText());
           ps.setInt(8, Integer.parseInt(selectrent.getText()));
           ps.execute();
            JOptionPane.showMessageDialog(null, "Your entry added Successfully");
          }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please !! Fill Correct Entries");
        }
    }//GEN-LAST:event_addentrybuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        selectplotnumber.setText("");
        selectcquantity.setText("");
        selecteno.setText("");                              
        selectstockname.setText("");
        selectrent.setText("");
       
       
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        close();
        MenuSelection ms=new MenuSelection();
        ms.setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void selectcquantityAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_selectcquantityAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcquantityAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRentEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel PageHeading;
    private javax.swing.JButton addentrybutton;
    private javax.swing.JButton back;
    private javax.swing.JLabel cquantity;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel date;
    private javax.swing.JLabel eno;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel note;
    private javax.swing.JLabel plotnumber;
    private javax.swing.JLabel product;
    private javax.swing.JLabel rent;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField selectcquantity;
    private javax.swing.JComboBox<String> selectcustomer;
    private com.toedter.calendar.JDateChooser selectdate;
    private javax.swing.JTextField selecteno;
    private javax.swing.JTextField selectplotnumber;
    private javax.swing.JComboBox<String> selectproduct;
    private javax.swing.JTextField selectrent;
    private javax.swing.JTextField selectstockname;
    private javax.swing.JLabel stockname;
    // End of variables declaration//GEN-END:variables
   private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\truck.png")));
    }
    public void close(){
    WindowEvent we=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
}
    private void setCustomer(){
    try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           PreparedStatement ps=con.prepareStatement("select CustName from RentalCustomerDetails");
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
          selectcustomer.addItem(rs.getString("CustName"));
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Problem in to assign values in ComboBox");
       }
    }
}
