
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush
 */
public class EditEntry extends javax.swing.JFrame {

    /**
     * Creates new form EditEntry
     */
    public EditEntry() {
        initComponents();
        setResizable(false);
        setTitle("Edit Entry");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditPannel = new javax.swing.JPanel();
        EntryNumber = new javax.swing.JLabel();
        SelectEntryNumber = new javax.swing.JTextField();
        ShowButt = new javax.swing.JButton();
        BeforeEditPannel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BeforeEditTable = new javax.swing.JTable();
        Column = new javax.swing.JLabel();
        SelectColumn = new javax.swing.JComboBox<>();
        NewValue = new javax.swing.JLabel();
        SelectNewValue = new javax.swing.JTextField();
        AfterEditPannel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AfterEditTable = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EditPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Edit Entry", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        EntryNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EntryNumber.setText("Enter Entry Number :");

        ShowButt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowButt.setText("Show");
        ShowButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditPannelLayout = new javax.swing.GroupLayout(EditPannel);
        EditPannel.setLayout(EditPannelLayout);
        EditPannelLayout.setHorizontalGroup(
            EditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPannelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(EntryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectEntryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ShowButt)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        EditPannelLayout.setVerticalGroup(
            EditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPannelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(EditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowButt)
                    .addComponent(SelectEntryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(EntryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        BeforeEditPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Before Editing", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        BeforeEditTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BeforeEditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Entry Number", "Quantity(C)", "Product", "Rate(C)", "Rent", "Plot Number", "Stock Name", "Quantity(S)", "Rate(S)", "Filling"
            }
        ));
        jScrollPane3.setViewportView(BeforeEditTable);

        javax.swing.GroupLayout BeforeEditPannelLayout = new javax.swing.GroupLayout(BeforeEditPannel);
        BeforeEditPannel.setLayout(BeforeEditPannelLayout);
        BeforeEditPannelLayout.setHorizontalGroup(
            BeforeEditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BeforeEditPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BeforeEditPannelLayout.setVerticalGroup(
            BeforeEditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BeforeEditPannelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Column.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Column.setText("Select Column     :");

        SelectColumn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EntryDate", "EntryNumber", "CQuantity", "Product", "CRate", "Rent", "PlotNumber", "StockName", "SQuantity", "SRate", "Filling" }));

        NewValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewValue.setText("Enter New Value :");

        SelectNewValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        AfterEditPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "After Editing", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        AfterEditTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AfterEditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Entry Number", "Quantity(C)", "Product", "Rate(C)", "Rent", "Plot Number", "Stock Name", "Quantity(S)", "Rate(S)", "Filling"
            }
        ));
        jScrollPane4.setViewportView(AfterEditTable);

        javax.swing.GroupLayout AfterEditPannelLayout = new javax.swing.GroupLayout(AfterEditPannel);
        AfterEditPannel.setLayout(AfterEditPannelLayout);
        AfterEditPannelLayout.setHorizontalGroup(
            AfterEditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterEditPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AfterEditPannelLayout.setVerticalGroup(
            AfterEditPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterEditPannelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AfterEditPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewValue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Column, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SelectNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SelectColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BeforeEditPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(18, 18, 18)
                .addComponent(EditPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BeforeEditPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Column, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewValue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AfterEditPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtActionPerformed
      try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
           int eno=Integer.parseInt(SelectEntryNumber.getText());
           PreparedStatement ps=con.prepareStatement("select * from AddEntry where EntryNumber="+eno+" ");
           ResultSet rs=ps.executeQuery();
           DefaultTableModel dtm=( DefaultTableModel)BeforeEditTable.getModel();
           dtm.setRowCount(0);
           while(rs.next()){
           Object o[]={rs.getDate("EntryDate"),rs.getInt("EntryNumber"),rs.getInt("CQuantity"),rs.getString("Product"),rs.getDouble("CRate"),rs.getInt("Rent"),rs.getString("PlotNumber"),rs.getString("StockName"),rs.getInt("SQuantity"),rs.getDouble("SRate"),rs.getInt("Filling")};
           dtm.addRow(o);
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_ShowButtActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
    close();
    MenuSelection ms=new MenuSelection();
    ms.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pawandb","root","");
        String prod=SelectColumn.getSelectedItem().toString();       
        PreparedStatement ps=con.prepareStatement("UPDATE AddEntry SET  "+prod+" = '"+SelectNewValue.getText()+"' WHERE EntryNumber = "+SelectEntryNumber.getText());               
        ps.execute();
        JOptionPane.showMessageDialog(null, "Update successfully");
           
           int eno=Integer.parseInt(SelectEntryNumber.getText());
           PreparedStatement ps1=con.prepareStatement("select * from AddEntry where EntryNumber="+eno+" ");
           ResultSet rs=ps1.executeQuery();
           DefaultTableModel dtm=( DefaultTableModel)AfterEditTable.getModel();
           dtm.setRowCount(0);
           while(rs.next()){
           Object o[]={rs.getDate("EntryDate"),rs.getInt("EntryNumber"),rs.getInt("CQuantity"),rs.getString("Product"),rs.getDouble("CRate"),rs.getInt("Rent"),rs.getString("PlotNumber"),rs.getString("StockName"),rs.getInt("SQuantity"),rs.getDouble("SRate"),rs.getInt("Filling")};
           dtm.addRow(o);
           }
           }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEntry().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify                     
    // End of variables declaration                   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AfterEditPannel;
    private javax.swing.JTable AfterEditTable;
    private javax.swing.JButton Back;
    private javax.swing.JPanel BeforeEditPannel;
    private javax.swing.JTable BeforeEditTable;
    private javax.swing.JLabel Column;
    private javax.swing.JPanel EditPannel;
    private javax.swing.JLabel EntryNumber;
    private javax.swing.JLabel NewValue;
    private javax.swing.JComboBox<String> SelectColumn;
    private javax.swing.JTextField SelectEntryNumber;
    private javax.swing.JTextField SelectNewValue;
    private javax.swing.JButton ShowButt;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\truck.png")));
   
    }
     public void close(){
    WindowEvent we=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
}
}
